//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public long ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CategoryID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ToCustomerID { get; set; }
        public decimal Amount { get; set; }
        public decimal Fee { get; set; }
        public decimal AfterFee { get; set; }
        public int BranchID { get; set; }
        public int UserID { get; set; }
        public string Note { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
